import { MaterialProperties, DesignSpecifications } from "./types";

export interface Preset {
  id: string;
  name: string;
  description: string;
  materials: MaterialProperties;
  specs: DesignSpecifications;
}

export const PRESETS: Preset[] = [
  {
    id: "structural-210-no-additive",
    name: "Concreto Estructural 210 kg/cm² (Sin Aditivo)",
    description: "Diseño estándar clásico para vigas, losas y columnas en condiciones normales sin incorporación de aditivos.",
    materials: {
      cementSpecificGravity: 3.12,
      fineSpecificGravity: 2.576,
      fineFinenessModulus: 2.93,
      fineHumidity: 4.951,
      fineAbsorption: 1.502,
      fineLooseUnitWeight: 1520,
      coarseSpecificGravity: 2.560,
      coarseDryRoddedUnitWeight: 1916.761,
      coarseHumidity: 1.366,
      coarseAbsorption: 0.917,
      coarseMaxNominalSize: "3/4",
      coarseLooseUnitWeight: 1420,
      hasAdditive: false,
      additiveWaterReduction: 10,
      additiveDosage: 1.0,
      additiveSpecificGravity: 1.18,
    },
    specs: {
      specifiedStrength: 210,
      useStandardDeviation: false,
      standardDeviation: 35,
      slumpRange: "3-4",
      airEntrained: false,
      exposureLevel: "mild",
    },
  },
  {
    id: "structural-280-plastificante",
    name: "Concreto Alto 280 kg/cm² (Con Aditivo Reductor 10%)",
    description: "Mezcla de resistencia intermedia con aditivo reductor de agua (plastificante). Permite mantener trabajabilidad reduciendo cemento.",
    materials: {
      cementSpecificGravity: 3.12,
      fineSpecificGravity: 2.63,
      fineFinenessModulus: 2.65,
      fineHumidity: 4.0,
      fineAbsorption: 1.0,
      fineLooseUnitWeight: 1520,
      coarseSpecificGravity: 2.70,
      coarseDryRoddedUnitWeight: 1620,
      coarseHumidity: 1.2,
      coarseAbsorption: 0.7,
      coarseMaxNominalSize: "3/4",
      coarseLooseUnitWeight: 1420,
      hasAdditive: true,
      additiveWaterReduction: 10,
      additiveDosage: 1.2,
      additiveSpecificGravity: 1.20,
    },
    specs: {
      specifiedStrength: 280,
      useStandardDeviation: false,
      standardDeviation: 35,
      slumpRange: "3-4",
      airEntrained: false,
      exposureLevel: "moderate",
    },
  },
  {
    id: "high-performance-350-superplastificante",
    name: "Alto Desempeño 350 kg/cm² (Superplastificante 18%)",
    description: "Fórmula de alta resistencia para estructuras masivas expuestas. Incluye aire incorporado por congelación extrema y superplastificante.",
    materials: {
      cementSpecificGravity: 3.15,
      fineSpecificGravity: 2.65,
      fineFinenessModulus: 2.80,
      fineHumidity: 3.5,
      fineAbsorption: 1.1,
      fineLooseUnitWeight: 1550,
      coarseSpecificGravity: 2.72,
      coarseDryRoddedUnitWeight: 1650,
      coarseHumidity: 1.0,
      coarseAbsorption: 0.6,
      coarseMaxNominalSize: "1",
      coarseLooseUnitWeight: 1450,
      hasAdditive: true,
      additiveWaterReduction: 18,
      additiveDosage: 1.5,
      additiveSpecificGravity: 1.22,
    },
    specs: {
      specifiedStrength: 350,
      useStandardDeviation: true,
      standardDeviation: 25,
      slumpRange: "3-4",
      airEntrained: true,
      exposureLevel: "severe",
    },
  },
  {
    id: "pavimentacion-foundation-250",
    name: "Pavimento / Zapata 250 kg/cm² (Reductor 8%)",
    description: "Excelente para cimentaciones pesadas o pavimentos, de consistencia plástica y aditivo economizador de agua.",
    materials: {
      cementSpecificGravity: 3.12,
      fineSpecificGravity: 2.62,
      fineFinenessModulus: 2.55,
      fineHumidity: 5.0,
      fineAbsorption: 1.5,
      fineLooseUnitWeight: 1500,
      coarseSpecificGravity: 2.67,
      coarseDryRoddedUnitWeight: 1580,
      coarseHumidity: 1.8,
      coarseAbsorption: 0.9,
      coarseMaxNominalSize: "1-1/2",
      coarseLooseUnitWeight: 1400,
      hasAdditive: true,
      additiveWaterReduction: 8,
      additiveDosage: 0.8,
      additiveSpecificGravity: 1.15,
    },
    specs: {
      specifiedStrength: 250,
      useStandardDeviation: false,
      standardDeviation: 30,
      slumpRange: "1-2",
      airEntrained: false,
      exposureLevel: "mild",
    },
  },
];
